# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bWpDPkPiovsAx5uTb2JXX+k0pULdkpDKLMp/zgJ1kC3s5RUBLGFmb6AC9RnXKoAMVzrtuPdnOm8BCrQnBrA5QDbZrEnR5bNaGYS8SQQeSaOq4j2y9vUS8M6oJTwCF/Es4qEAJYNTkZLilH5lfaJvHw7OK63CWBu0CfDidTkKo6aouNlGn9BQvB8puG3abquzBR1rRl33FJIq8HdzJz1KTUPrk6/QgYc4AVli8v8VtbJg/qw7cJdu5NprfSadIzqSdVV3o3ZLdxwXujMh7tkmVOlHSbr0Jvt+DxMKEnMdxZeHhOhJ1fhGly7a9liYLFUYU5TPQu9hq5GwV/g102mdIpKkOlhhBhgNrntG/J67uS7j5p5wLyNrTeH9glHwP6tQyWhXQCWZs+uPaVnzPj9J+dqk9iHC27L4P+EVYSsjCfAjXNi3UnoJz8bOXexTOBq+MB85jemnfWnogUcARZBoBo5hGA/KpKQ5u8SSAnQ7qwBm20IgTQFcfPGUdDM0O7H80WGQW+WHK16pbmC9Xv0vdKj9pJe4POuGklU2HhrPPdZBI6S4frLnZw7yeEozUTiLod7DF4Y+3TTz0mvuJno49Ddb+8kzFtbOkStpHl420s4NzqUeFwRVIo0SRQ67x2YjQjyXXeWZw77rwawKLFjFBmsSnG9WzqIF2UiUHxdHM5Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
