travis:
  secure:
    BINSTAR_TOKEN: dsDU8i87CLZuWKqtPJe8iqHDSU3gB3M+CHVCalr+LhxbghMRkTGqMZGLEi6lF3AqCEBAH3iKyFlvbTcyq3+ofvfrkGTRwhiwbEiV62Pp7qw+jOxjI9OeUs8n092fIPnWLeRLobEVNb8b+n0bBz7EX1YzY4GAuMkYSUMqS0P9n1uV2ZJMLn1NBARlTZ2i26OJmt2Slns9scPgo+4WlMtD1erZEyBt9Xy9x2Ov1B4H9R0/JwEznElHlkajZPEp85jlGR0r2VijlpMXsBi3SYpqaKA5dDuWHnTQ8hRvssi95KI4o1FNFSDv0H7MPMZ4WtZSzW9wAUFg5lC1ePY1RIyA386JYIiS9HT59i63cB+yFYBo0O/CVIh33ddoApJ+wjOuSd4FN+IFRw5UqMzvO6MnmmJ0RfIkhYbxYKFrxok0qdtVZY74A5YfZOxR0/XmYLvwQT5T8LKn8ElfuTEQs5nE4BKZ28qEaIF6iLDgq9Vey9/ylHLcRk7rm2moWgG+U8KwVAxFp6Pf8qbwu/V0XT7G+gDVAhkwpj9bSAmJt49VGPA/fFhBpjfsjvsZtCaKU0qGyQYtxhFn9YugXCeOm+i7i+fifUl6fTfS/xoIaVIb4ciOUdWzhAycSaJOlNboTAhrRaNrXpbhsW3HInQuDkT6cfCk7qN6U8sychtG9JhqhzU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
