travis:
  secure:
    BINSTAR_TOKEN: bWpDPkPiovsAx5uTb2JXX+k0pULdkpDKLMp/zgJ1kC3s5RUBLGFmb6AC9RnXKoAMVzrtuPdnOm8BCrQnBrA5QDbZrEnR5bNaGYS8SQQeSaOq4j2y9vUS8M6oJTwCF/Es4qEAJYNTkZLilH5lfaJvHw7OK63CWBu0CfDidTkKo6aouNlGn9BQvB8puG3abquzBR1rRl33FJIq8HdzJz1KTUPrk6/QgYc4AVli8v8VtbJg/qw7cJdu5NprfSadIzqSdVV3o3ZLdxwXujMh7tkmVOlHSbr0Jvt+DxMKEnMdxZeHhOhJ1fhGly7a9liYLFUYU5TPQu9hq5GwV/g102mdIpKkOlhhBhgNrntG/J67uS7j5p5wLyNrTeH9glHwP6tQyWhXQCWZs+uPaVnzPj9J+dqk9iHC27L4P+EVYSsjCfAjXNi3UnoJz8bOXexTOBq+MB85jemnfWnogUcARZBoBo5hGA/KpKQ5u8SSAnQ7qwBm20IgTQFcfPGUdDM0O7H80WGQW+WHK16pbmC9Xv0vdKj9pJe4POuGklU2HhrPPdZBI6S4frLnZw7yeEozUTiLod7DF4Y+3TTz0mvuJno49Ddb+8kzFtbOkStpHl420s4NzqUeFwRVIo0SRQ67x2YjQjyXXeWZw77rwawKLFjFBmsSnG9WzqIF2UiUHxdHM5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
